services:
  - type: web
    name: mayan-edms
    env: docker
    plan: free
    autoDeploy: false
    image:
      url: mayanedms/mayanedms:latest
    envVars:
      - key: MAYAN_SETTINGS_MODULE
        value: mayan.settings.production
    disk:
      name: mayan_data
      mountPath: /var/lib/mayan
      sizeGB: 10
